//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApprovalPolicy) DeepCopyInto(out *ApprovalPolicy) {
	*out = *in
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = new(bool)
		**out = **in
	}
	if in.AllowedApprovers != nil {
		in, out := &in.AllowedApprovers, &out.AllowedApprovers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApprovalPolicy.
func (in *ApprovalPolicy) DeepCopy() *ApprovalPolicy {
	if in == nil {
		return nil
	}
	out := new(ApprovalPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtifactReference) DeepCopyInto(out *ArtifactReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtifactReference.
func (in *ArtifactReference) DeepCopy() *ArtifactReference {
	if in == nil {
		return nil
	}
	out := new(ArtifactReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetPreparationSpec) DeepCopyInto(out *DatasetPreparationSpec) {
	*out = *in
	out.OutputRef = in.OutputRef
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetPreparationSpec.
func (in *DatasetPreparationSpec) DeepCopy() *DatasetPreparationSpec {
	if in == nil {
		return nil
	}
	out := new(DatasetPreparationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatasetReference) DeepCopyInto(out *DatasetReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatasetReference.
func (in *DatasetReference) DeepCopy() *DatasetReference {
	if in == nil {
		return nil
	}
	out := new(DatasetReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftMonitoringSpec) DeepCopyInto(out *DriftMonitoringSpec) {
	*out = *in
	out.BaselineRef = in.BaselineRef
	out.CurrentFeaturesRef = in.CurrentFeaturesRef
	out.ReportRef = in.ReportRef
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftMonitoringSpec.
func (in *DriftMonitoringSpec) DeepCopy() *DriftMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(DriftMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvaluationPolicy) DeepCopyInto(out *EvaluationPolicy) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvaluationPolicy.
func (in *EvaluationPolicy) DeepCopy() *EvaluationPolicy {
	if in == nil {
		return nil
	}
	out := new(EvaluationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GovernancePolicy) DeepCopyInto(out *GovernancePolicy) {
	*out = *in
	out.ResourceBounds = in.ResourceBounds
	in.Approval.DeepCopyInto(&out.Approval)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GovernancePolicy.
func (in *GovernancePolicy) DeepCopy() *GovernancePolicy {
	if in == nil {
		return nil
	}
	out := new(GovernancePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelApproval) DeepCopyInto(out *ModelApproval) {
	*out = *in
	in.ApprovedAt.DeepCopyInto(&out.ApprovedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelApproval.
func (in *ModelApproval) DeepCopy() *ModelApproval {
	if in == nil {
		return nil
	}
	out := new(ModelApproval)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutcomeMonitoringSpec) DeepCopyInto(out *OutcomeMonitoringSpec) {
	*out = *in
	out.ReportRef = in.ReportRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutcomeMonitoringSpec.
func (in *OutcomeMonitoringSpec) DeepCopy() *OutcomeMonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(OutcomeMonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceBoundsPolicy) DeepCopyInto(out *ResourceBoundsPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceBoundsPolicy.
func (in *ResourceBoundsPolicy) DeepCopy() *ResourceBoundsPolicy {
	if in == nil {
		return nil
	}
	out := new(ResourceBoundsPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskModel) DeepCopyInto(out *RiskModel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskModel.
func (in *RiskModel) DeepCopy() *RiskModel {
	if in == nil {
		return nil
	}
	out := new(RiskModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RiskModel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskModelEvidence) DeepCopyInto(out *RiskModelEvidence) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskModelEvidence.
func (in *RiskModelEvidence) DeepCopy() *RiskModelEvidence {
	if in == nil {
		return nil
	}
	out := new(RiskModelEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskModelLineage) DeepCopyInto(out *RiskModelLineage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskModelLineage.
func (in *RiskModelLineage) DeepCopy() *RiskModelLineage {
	if in == nil {
		return nil
	}
	out := new(RiskModelLineage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskModelList) DeepCopyInto(out *RiskModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RiskModel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskModelList.
func (in *RiskModelList) DeepCopy() *RiskModelList {
	if in == nil {
		return nil
	}
	out := new(RiskModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RiskModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskModelSpec) DeepCopyInto(out *RiskModelSpec) {
	*out = *in
	out.DatasetRef = in.DatasetRef
	in.Preparation.DeepCopyInto(&out.Preparation)
	in.Evaluation.DeepCopyInto(&out.Evaluation)
	in.DriftMonitoring.DeepCopyInto(&out.DriftMonitoring)
	out.OutcomeMonitoring = in.OutcomeMonitoring
	out.OutputRef = in.OutputRef
	out.Lineage = in.Lineage
	in.Resources.DeepCopyInto(&out.Resources)
	in.Serving.DeepCopyInto(&out.Serving)
	in.Policy.DeepCopyInto(&out.Policy)
	if in.Approvals != nil {
		in, out := &in.Approvals, &out.Approvals
		*out = make([]ModelApproval, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskModelSpec.
func (in *RiskModelSpec) DeepCopy() *RiskModelSpec {
	if in == nil {
		return nil
	}
	out := new(RiskModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RiskModelStatus) DeepCopyInto(out *RiskModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PromotedAt != nil {
		in, out := &in.PromotedAt, &out.PromotedAt
		*out = (*in).DeepCopy()
	}
	if in.DriftObservedAt != nil {
		in, out := &in.DriftObservedAt, &out.DriftObservedAt
		*out = (*in).DeepCopy()
	}
	if in.OutcomeCoverage != nil {
		in, out := &in.OutcomeCoverage, &out.OutcomeCoverage
		*out = new(int32)
		**out = **in
	}
	if in.OutcomeRecall != nil {
		in, out := &in.OutcomeRecall, &out.OutcomeRecall
		*out = new(int32)
		**out = **in
	}
	if in.OutcomeObservedAt != nil {
		in, out := &in.OutcomeObservedAt, &out.OutcomeObservedAt
		*out = (*in).DeepCopy()
	}
	if in.ApprovedBy != nil {
		in, out := &in.ApprovedBy, &out.ApprovedBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]RiskModelEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RiskModelStatus.
func (in *RiskModelStatus) DeepCopy() *RiskModelStatus {
	if in == nil {
		return nil
	}
	out := new(RiskModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServingConfig) DeepCopyInto(out *ServingConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServingConfig.
func (in *ServingConfig) DeepCopy() *ServingConfig {
	if in == nil {
		return nil
	}
	out := new(ServingConfig)
	in.DeepCopyInto(out)
	return out
}
